// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// analytics renders the site's third-party analytics tag into a document head.
// It is the single place any tracker is mounted, shared by all three self-
// contained documents (Layout, LandingPage, SandboxesPage) so the snippet is
// written once rather than copied into three heads that would then drift.
//
// It renders NOTHING when no client id is configured. That is the common case
// for a self-hosted or local-mode install, a test run and a dev box, and none of
// them should ship a beacon to a vendor: tracking is opt-in, enabled only by
// setting OPENPANEL_CLIENT_ID.
//
// The snippet is emitted via templ.Raw because templ does not evaluate
// expressions inside a literal <script> tag — see openPanelScript, which builds
// the whole element (and escapes the id) for exactly that reason.
func analytics() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if OpenPanelClientID != "" {
			templ_7745c5c3_Err = templ.Raw(openPanelScript(OpenPanelClientID)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
